result_prefix: 'llama3_customized'
dataset: '/home/ubuntu/agentv-main/email_agent/dataset/combined_test.csv'
generation:
  model: "meta-llama/Meta-Llama-3-8B"
  checkpoint: "/home/ubuntu/agentv-main/checkpoints/llama3/customized/checkpoint-48"
  device: "cuda:0"
verification:
  enable: False
configs:
  save_detailed_results: True
  folder: 'results'